### ISSUE TITLE
publish on melpa

### ISSUE THREAD

**Issue by wbolster** [wbolster/emacs-python-pytest#1]
https://github.com/melpa/melpa/pull/5286

**Comment by thomasluquet** [comment]
Don't forget the licence file.

**Comment by wbolster** [comment]
it's in the readme already:

https://github.com/wbolster/emacs-python-pytest/blob/master/README.rst#license

**Comment by wbolster** [comment]
update: addressed some reviewer comments from @purcell: https://github.com/melpa/melpa/pull/5286#issuecomment-366231211

**Comment by wbolster** [comment]
https://melpa.org/#/python-pytest  🎉
