### ISSUE TITLE
--color is not enabled by default

### ISSUE THREAD

**Issue by valignatev** [wbolster/emacs-python-pytest#12]
Hi! Thanks for the project!
According to this `t` here: https://github.com/wbolster/emacs-python-pytest/blob/master/python-pytest.el#L139 and to the `magit-popup` manual, `--color` should be enabled by default, but apparently it's not. Am I missing something or it's a bug somewhere in `emacs-python-pytest` or in `magit-popup`?

**Comment by wbolster** [comment]
hmm, seems this package is not to blame, since as you said it's supposed to be on by default. do you have settings in our init.el (also check what `Customize` did)?

**Comment by valignatev** [comment]
For some reason, it's still off by default for me. But I've noticed that the color switch works well, and I've run `magit-popup-set-default-arguments` with the  `magit-popup-save-default-arguments`. It saved the `python-pytest-arguments` setting to my custom file and now it persists across Emacs restarts. Hope it'll help somebody.

**Comment by wbolster** [comment]
perhaps deifning the pop-up with a default is not enough. i may have a look later.
