### ISSUE TITLE
Enhance pytest buffer (read-only, navigation, closing)

### ISSUE THREAD

**Issue by benbovy** [wbolster/emacs-python-pytest#13]
Thanks for sharing this package which is very useful!

Just a small suggestion: it would be nice to add in pytest buffers things that are available, e.g., in the [compilation-mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html), like read-only buffer, keys to navigate from one error to another, `q` key for closing the window, etc.

**Comment by wbolster** [comment]
glad you like it!

i am not sure what you suggest is possible. i use `pytest` buffers a lot in combination with a `pdb` debugging shell.  read-only buffers would break that. also shortcuts like `q` would prevent typing in `pdb` sessions.

**Comment by wbolster** [comment]
also not that since i added some code for #7 the built-in `next-error` (and friends) seem to work for basic cases.

**Comment by benbovy** [comment]
Oh I see, I don't use (yet) `pdb` in emacs but it makes perfect sense not to have a read-only buffer. `q` would have been convenient, but it is not a big deal.

And oops I haven't seen #7, `next-error` works fine! Still, what I miss is a key for `compilation-next-error` but `M-p` is used by both by `compilation-mode` and `comint-mode` (pytest mode derives from the latter). I guess I can find a workaround for this.

**Comment by wbolster** [comment]
you should be able to configure those key bindings in `python-pytest-mode-map`. for instance, i have this in my `init.el` to add custom bindings (note that i use evil-mode but it should work without as well):

``` emacs
(use-package python-pytest
  :demand t
  :after python
  :custom
  (python-pytest-arguments
   '("--color"
     "--failed-first"
     "--maxfail=10"))
  :general
  (:keymaps 'python-pytest-mode-map
   :states 'motion
   "g r" #'python-pytest-repeat))
```

**Comment by benbovy** [comment]
I ended up using this:

```elisp
(use-package python-pytest
  :custom
  (python-pytest-arguments
   '("--color"))
  :bind (:map python-pytest-mode-map
              ("M-p" . compilation-previous-error)
              ("M-n" . compilation-next-error)))
```

Thanks!

**Comment by wbolster** [comment]
cool!
