### ISSUE TITLE
Rerun last, but allow changing options

### ISSUE THREAD

**Issue by matthew-piziak** [wbolster/emacs-python-pytest#16]
This package supports the following usecases:
- rerun the last run immediately, exactly as is
- start configuring a new run from scratch

Now, a common pattern is to request "run the last invocation, _but_ with the verbose flag turned on". It would be nice if this package supported that. The easiest way I think would be to show the pytest menu with all the previous run's flags enabled.

**Comment by wbolster** [comment]
this is supposed to work if you invoke the popup from the pytest buffer. the python-pytest-popup-arguments variable is set in that buffer, and the popup is supposed to pick that up

**Comment by matthew-piziak** [comment]
Interesting. I don't have `python-pytest-popup-arguments` defined in my pytest buffer, just `python-pytest-popup`. Might be something to do with my particular setup. I'll experiment a bit more.

**Comment by matthew-piziak** [comment]
Okay, it does work for some switches. I think it's just that it doesn't work for custom switches added with `transient`. Thanks for tip!

**Comment by wbolster** [comment]
yw! also you can use the repeat command with a prefix arg (C-u) and just type `-v` at the end.

i realise this is not perfect but it does help me in practice :)

**Comment by wbolster** [comment]
oh, and magit-popup lets you save defaults. use C-t in the popup

**Comment by matthew-piziak** [comment]
Emacs just keeps getting better and better. Thank you!

**Comment by matthew-piziak** [comment]
I think this all works now. Thanks again!
