### ISSUE TITLE
python -m pytest functionality 

### ISSUE THREAD

**Issue by rOY369** [wbolster/emacs-python-pytest#19]
I want to add the current directory to sys.path which happens to be the case when i run 'python -m pytest'. How to achieve the same functionality with emacs-python-pytest ?

**Comment by wbolster** [comment]
i typically use a virtualenv and installing your project in it (in development mode).

what's the command you want to run exactly?

**Comment by rOY369** [comment]
Got it. I used setenv to set PYTHONPATH in init.el to add the directory in sys.path. Thanks anyway !

**Comment by wbolster** [comment]
great!

btw, you may be interested in my emacs-direnv package to do stuff like this
