### ISSUE TITLE
Fix MELPA Stable build

### ISSUE THREAD

**Issue by ccharles** [wbolster/emacs-python-pytest#2]
The current build of `emacs-python-pytest` on MELPA Stable [depends on `dash` version 2.12.0][1].

Unfortunately, that version of `dash` lacks the `-as->` macro, which was introduced in [commit `a3b40f8f`][2]. No released version of `dash` includes this macro, though an [issue exists requesting a new release][3].

Please update the dependencies once a new version of `dash` is released (or rewrite the stable functionality so it doesn't depend on unreleased features, but this is obviously less desirable for several reasons).

[1]: https://github.com/wbolster/emacs-python-pytest/blob/75c6c131f6d67ebb6edc530d9a34d1bd2194e834/python-pytest.el#L5
[2]: https://github.com/magnars/dash.el/commit/a3b40f8f01d12c118037c9045e30ceaac7068cd9
[3]: https://github.com/magnars/dash.el/issues/243

**Comment by wbolster** [comment]
@ccharles  bc3addcd6114ca413c7d3ceaae34cdfa153665c8 avoids the use of `-as->` for poor souls like you who stick to ‘stable’ stuff. ;)

just tagged 0.2.2, should appear on melpa stable in a bit. please give it a try and report back!

**Comment by ccharles** [comment]
> please give it a try and report back!

Version 0.2.2 is working now. Thanks!

**Comment by basil-conto** [comment]
Note that both [GNU ELPA](https://elpa.gnu.org/packages/dash.html) and [MELPA Stable](https://stable.melpa.org/#/dash) have Dash 2.18.0 now.

**Comment by wbolster** [comment]
thanks for the heads-up. it's not worth it to reintroduce `-as->` usage; the code is just fine without it.
