### ISSUE TITLE
silly question: how can I add default args to the pytest command

### ISSUE THREAD

**Issue by cmorgan** [wbolster/emacs-python-pytest#20]
e.g. i want to always have "-s" to the command.
I'm not too familiar with magit or even elisp macros - could you provide some help?
Cheers!

**Comment by wbolster** [comment]
i use the `magit-popup` support for that, which gives a customisable `python-pytest-arguments` variable, which i use via `use-package` `:custom` keyword, like so:

```elisp
(use-package python-pytest
  :demand t
  :after python
  :custom
  (python-pytest-arguments
   '("--color"
     "--failed-first"
     "--maxfail=10"
     "--verbose")))
```
