### ISSUE TITLE
running tests from popup does not work with venv from poetry-tracking-mode

### ISSUE THREAD

**Issue by stfl** [wbolster/emacs-python-pytest#23]
I use poetry for dependency management.
poetry-mode has poetry-tracking-mode that automatically activates the poetry created venv which is located in ~/.cache/pypoetrey/virtualenvs/...

running the test directly with `M-x python-pytest-file` works as expected.
Going through the popup and then `F` to run the tests on a file fails with `/usr/bin/sh: 1: pytest: not found`
I have pytest only installed as a dev dependency through poetry.

I am fairly new to pytest and emacs so please let me know how I can provide more relevant logs or details.

**Comment by wbolster** [comment]
note: i don't use poetry myself.

i guess this is a problem with poetry-tracking-mode somehow deactivating the `virtualenv` in the buffer that shows the popup (the menu provided by this package).

i'm not sure why poetry has special emacs support for virtualenvs, but i (and many others) use [`direnv.el`](https://github.com/wbolster/emacs-direnv) (aka emacs-direnv) to track environments and automatically change them. `python-pytest.el` (this package) works very well with direnv.

`direnv` is orthogonal to other tools such as `poetry` and can do many things, including activating/deactivating virtualenvs (changing `$PATH` and `$VIRTUAL_ENV` env vars, basically). i assume that poetry has a way to obtain the path to the `virtualenv` to use. an `.envrc` file for `direnv` could look like this:

``` bash
VIRTUAL_ENV="$(poetry ...)"  # obtain path to virtualenv directory somehow
PATH_add "$VIRTUAL_ENV/bin"
```

**Comment by stfl** [comment]
Thank you very much for the explanation. I will give direnv.el a try.

**Comment by wbolster** [comment]
fwiw, moving to `transient.el` (see #26) may also help, since it works differently from `magit-popup.el`.

(i stand by my `direnv` comment still; it will also help with various other things inside emacs that require the environment to be set up correctly.)
