### ISSUE TITLE
DWIM commands aren't working

### ISSUE THREAD

**Issue by jtpavlock** [wbolster/emacs-python-pytest#30]
Hey! Thanks for creating this awesome package.

I'm having a weird issue that's not a huge deal, but none of the DWIM commands are working for me, but the non-DWIM ones are. 

The outout of any DWIM command is `No test file found`

Any idea what could be causing this?

Also, as an unrelated question, is there any way to control which buffer pytest will send its output to?

Thanks in advance!

**Comment by wbolster** [comment]
hmmm that's weird. the dwim commands try to automagically select the right file, function etc.

- the *file* helpers come directly from projectile.el. its heuristics are based on file name patterns as far as i know.

- the heuristics to find test *functions* are implemented in this package, but those also use projectile under the hood.

so i guess your project has some directory structure or naming convention that projectile can't understand.

**Comment by wbolster** [comment]
re the buffer: this package creates a new one automatically, or reuses an existing buffer that it created in a previous run.

there's a config flag to use a different buffer per project (it adds the project name to the buffer name)

**Comment by wbolster** [comment]
feel free to describe your use cases and how this package gets in the way. the current design is, as expected, centered about how i use pytest and emacs myself, but that may not be ideal for others

**Comment by jtpavlock** [comment]
hmm.. my project structure is 
```
├── moe
│   ├── cli.py
│   ├── config.py
│   ├── __init__.py
│   ├── lib
│   │   ├── __init__.py
│   │   ├── library.py
│   ├── plugins
│   │   ├── add.py
│   │   ├── __init__.py
│   └── py.typed
├── poetry.lock
├── poetry.toml
├── pyproject.toml
├── README.rst
├── setup.cfg
└── tests
    ├── __init__.py
    ├── test_cli.py
    └── test_config.p
```
Which I thought seemed normal.

**Comment by jtpavlock** [comment]
I think it is indeed an issue with projectile as `M-x projectile-find-test-file` results in an empty set.

**Comment by wbolster** [comment]
that structure looks quite normal indeed. it's a lot like some of my projects (for which the projectile helpers work).

i would be interested to learn what's "wrong".

**Comment by jtpavlock** [comment]
Fixed by adding 
```
;; Projectile project type - Python + pytest
(after! projectile
(projectile-register-project-type 'python-poetry '("poetry.lock")
                                  :project-file "poetry.lock"
                                  :compile "poetry build"
                                  :test "pytest"
                                  :test-dir "tests"
                                  :test-prefix "test_"
                                  :test-suffix"_test"
                                  )
)
```
to `init.el`

It seems projectile doesn't currently support poetry-based projects. I'll submit a patch to add this in upstream.
