### ISSUE TITLE
requires direnv

### ISSUE THREAD

**Issue by flub** [wbolster/emacs-python-pytest#33]
When I have this in my startup file:
```
(require 'python-pytest)
(require 'direnv)
```
startup fails with:
```
Symbol's value as variable is void: direnv-non-file-modes
```
Switching the two lines around fixes this.

I guess you might as well just directly depend on direnv?

**Comment by wbolster** [comment]
yeah, it seems i broke this a few days ago without thinking it through: https://github.com/wbolster/emacs-python-pytest/commit/54f23a654bb502e54aa40d156d281f5902dc3fa1

but i reverted it yesterday: https://github.com/wbolster/emacs-python-pytest/commit/fc056faf2757c42641ed94d36a090e56eb13572f

i guess the latest melpa version should work for you?

**Comment by flub** [comment]
indeed, latest melpa doesn't have that issue anymore.  thanks!

**Comment by wbolster** [comment]
thanks for reporting anyway, i didn't see this issue myself at first.
