### ISSUE TITLE
Broken with Emacs 28.x

### ISSUE THREAD

**Issue by rassie** [wbolster/emacs-python-pytest#40]
Emacs 28.x updates the signature of `define-obsolete-function-alias` to make a previously optional parameter required (https://github.com/emacs-mirror/emacs/commit/32c6732d16385f242b1109517f25e9aefd6caa5c). Since `emacs-python-pytest` uses the old syntax, it's broken with Emacs 28.x.

**Comment by wbolster** [comment]
thanks for the detailed report. 🙏 sounds like an easy fix. care to open a pr?

**Comment by rassie** [comment]
I can try, but I'd prefer someone familiar with the code to do it -- I'm more or less an advanced user, but not even close to being a beginner ELisp coder. Adding a parameter is not a problem, making sure it doesn'r break anything is a completely different matter...

**Comment by wbolster** [comment]
no worries about compatibility, it's only adding a arg this case:

https://github.com/wbolster/emacs-python-pytest/blob/master/python-pytest.el#L158

if you want to test you can copy/paste it to your scratch buffer, tweak it, then eval it (C-x C-e from the top of my head)

(you can even make a pr using the github web interface)

**Comment by rassie** [comment]
Take a look at #41 please, should be correct now.
