### ISSUE TITLE
Set working directory

### ISSUE THREAD

**Issue by FredrikMeyer** [wbolster/emacs-python-pytest#42]
Thanks for a great package!

My situation is this. We have a monorepo at work with several Python projects in it. When I run `python-pytest-file`, it chooses the repo root as the working directory, from where it can't find the module being tested.

In  my case the directory I want to run pytest from is somewhere in the middle between the root and the test file.

Is it possible to somehow set the working directory?

And if not, it's a feature request :)

**Comment by wbolster** [comment]
i understand the issue and making it work in such situations would indeed be usfeul.

that said, i think it would be best if you can somehow convince `projectile` what the ‘root’ of your project it is, since `emacs-python-pytest` uses `projectile` for quite a few things, one of which is finding the right directory to run from. (another example is finding matching test files and so on.)

**Comment by wbolster** [comment]
https://docs.projectile.mx/projectile/projects.html

this may be useful. perhaps it makes sense to search for `pytest.ini` or something like that? it wouldn't be water tight since pytest options can also be set from different config files. 🤔

**Comment by FredrikMeyer** [comment]
Thanks for the answer!

I started down a little rabbit hole to see if I could temporarily change the `projectile-project-root` variable. I first tried adding it in `.dir-locals.el` but that messes things up with Projectile itself. Then I saw that you have the option to run hooks before and after the tests are run, so my idea was to read `.dir-locals.el` for some flag, and before the test run the `projectile-project-root` to the package directory, and then reset it afterwards.

But after inspecting the source code, I found that these hooks are run after the pytest buffer is created, so the method won't work.

So it looks like maybe one has to changes in pytest.el itself, maybe.

**Comment by FredrikMeyer** [comment]
Hm! I got an idea on how to get this to work: use the pre test hook to look in `.dir-locals.el` for some custom variable, then temporarily change the `pytest` command to `PYTHONPATH=path/to/my/package pytest`.

I'll test it later today.

**Comment by FredrikMeyer** [comment]
Update:

I think I solved it :) 

I added the following hook:
```
  (add-hook 'python-mode-hook
            (lambda ()
              (when-let ((r (locate-dominating-file default-directory ".pyroot")))
                       (setq python-pytest-executable (concat "PYTHONPATH=" r " python -m pytest"))
                       )))
```
Then if I have a `.pyroot` file in the root of the project, the project is added to PYTHONPATH, and `pytest` finds the modules.

**Comment by wbolster** [comment]
awesome, that sounds like a reasonable  solution! it won't even clash with projectile's behaviour that way.

**Comment by pkryger** [comment]
Do you think it would be a good idea to add this snippet with an explanation of the problem it solves to the readme?

**Comment by FredrikMeyer** [comment]
@pkryger Personally I really like it when Readmes contain solutions to common problems :) But if the issues list is labelled well, that could also help.

**Comment by wbolster** [comment]
pull requests to improve the readme are always welcome 😉
