### ISSUE TITLE
Add mode CLI args

### ISSUE THREAD

**Issue by dorneanu** [wbolster/emacs-python-pytest#43]
Hi! I would like to add the `-s` switch in order to capture stdout/stderr. How can I do that with your package?

Thanks in advance.

**Comment by wbolster** [comment]
have you tried typing literally `-s` from the menu? 😁

**Comment by wbolster** [comment]
it looks like this in the menu:

```
 -s no output capture (--capture=no)
```

**Comment by dorneanu** [comment]
Which menu do you mean? I run that specific function using `, t t` in doom-emacs.

**Comment by wbolster** [comment]
`M-x python-pytest-dispatch`

see the readme?

**Comment by dorneanu** [comment]
yes i see that, but how can i modify `pyhon-pytest-function` to have `-s` included? I don't want to call that menu every time.

**Comment by wbolster** [comment]
this packages uses `transient.el`, which is also used by `magit`. you can use transient to save settings: https://magit.vc/manual/transient/Saving-Values.html

**Comment by dorneanu** [comment]
Ah! Thank you very much.

**Comment by wbolster** [comment]
note that the `transient.el` change was relatively recent, and not everything may work perfectly, so there may be some rough edges here and there… 🙈

**Comment by dorneanu** [comment]
but it worked. for my purposes it works perfectly fine.

**Comment by sammorley-short** [comment]
I have a similar issue where I (in doom) have mapped running some of this package's commands to shortcuts

E.g.:

```elisp
(map! :leader :desc "Test file" :n "r f" 'python-pytest-file-dwim)
```

However, I would prefer if `python-pytest-file-dwim` was called with the verbose argument. I have taken a look at transient and am too much of an Emacs noob to understand it, but if you can suggest how I might achieve this some other way, that would be very helpful! 

Thanks!

**Comment by sammorley-short** [comment]
> this packages uses `transient.el`, which is also used by `magit`. you can use transient to save settings: https://magit.vc/manual/transient/Saving-Values.html

To add to my comment above, I'd like to do this in a way where I don't have to save transient option defaults for all other calls to `python-pytest-***`. So this fix wouldn't work in my case.
