### ISSUE TITLE
Set commonly used pytest flags as the default

### ISSUE THREAD

**Issue by ahonnecke** [wbolster/emacs-python-pytest#49]
Currently I add `--pdb` to the executable path so I don't have to select it every time that I run a test, but it seems rather hacky.  I think that it would be nice to have a set of default flags that populate as selected in the dispatch popup (that way on the rare occasion that I don't want --pdb set I can turn it off without changing the executable).

**Comment by pkryger** [comment]
Would [the transient save feature](https://github.com/wbolster/emacs-python-pytest/issues/43#issuecomment-782128908) work for you?

**Comment by ahonnecke** [comment]
I'd rather have it in a place where I can commit it.  That said, I would be eager to work on this if you would be open to a PR (and maybe point me in the right direction)

**Comment by wbolster** [comment]
https://github.com/wbolster/dotfiles/tree/main/emacs/etc/transient

i just commit those files 🙈

**Comment by wbolster** [comment]
i think transient.el already gets us 99% there including history etc. adding complexity to this project seems unnecessary and not worth it.
