### ISSUE TITLE
Text is read-only

### ISSUE THREAD

**Issue by apnewberry** [wbolster/emacs-python-pytest#5]
I run `python-pytest-popup`, press `t` for `Test all`, and it runs. Then I try to do it again, perhaps after changing some code, and I get `Text is read-only` in the minibuffer, and the tests won't run unless I kill the pytest buffer and re-run `python-pytest-popup`. 

Could you help me understand what I'm doing wrong?

emacs-python-pytest 0.3.1
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
Ubuntu 17.10
python 3.6.3
pytest 3.5.0

**Comment by wbolster** [comment]
hmm, that's weird. is the output buffer read-only perhaps? (if so, do you know why?)

**Comment by wbolster** [comment]
also, a backtrace may help: `M-x toggle-debug-on-error`

**Comment by apnewberry** [comment]
Aha, you're right, I had `comint-prompt-read-only` enabled and forgot about it! Thanks :)

**Comment by apnewberry** [comment]
Though perhaps this does raise a question: when I'm in the pytest buffer, without `comint-prompt-read-only`, I can type in the buffer, even if I'd never want to; on the other hand, if enable `comint-prompt-read-only`, `python-pytest` can't edit the buffer either. Perhaps something like [this answer](https://emacs.stackexchange.com/a/2897/9014) might address that:

```elisp
(setq comint-prompt-read-only t)

(defun my-comint-preoutput-turn-buffer-read-only (text)
  (propertize text 'read-only t))

(add-hook 'comint-preoutput-filter-functions 'my-comint-preoutput-turn-buffer-read-only)
```

If something like that would work it might be a nice little trick. As the asker notes in that question, it's more an aesthetic point than a practical one.

**Comment by jtpavlock** [comment]
Interestingly, it seems doom sets `comint-prompt-read-only` to true by default.
