### ISSUE TITLE
Dependency transient-20200719 not in MELPA

### ISSUE THREAD

**Issue by caleb-s-cullen** [wbolster/emacs-python-pytest#52]
I tried to install python-pytest today and MELPA will not let me install it because it depends on transient-20200719 rather than transient-0.3.7 and the former is not present in MELPA.  I am not sure how to install transient-20200719 except from its own git repo perhaps.

Any advice would be welcome.

**Comment by wbolster** [comment]
heh my commit message about the version bump (6256440) was spot on 🙃

> 3.1.0 for those poor souls using melpa stable

you do realize lots of stuff is ancient on melpa stable?

**Comment by wbolster** [comment]
ok i've changed the dependency and pushed a 3.2.0 tag. melpa stable will soon catch up 🤞🏼
