### ISSUE TITLE
Double verbosity setting saving broken

### ISSUE THREAD

**Issue by sammorley-short** [wbolster/emacs-python-pytest#63]
I'm finding that I can't permanently save the `-vv` (double verbosity) via `C-x C-s`. All the other settings I've used (such as `-x` and `--ff` save fine, but when I close and open emacs, the verbosity setting always reverts to `-v`.

Further details:

* Running Doom Emacs on OSX.
* Occurs regardless of the test mode (all, file, repeat)
* Double verbosity persists during repetitions, but not after that.

**Comment by wbolster** [comment]
i suspect this is something `transient.el` related

**Comment by juergenhoetzel** [comment]
> i suspect this is something `transient.el` related

Fixed by using stricter  `argument-regex` in #64 .
