### ISSUE TITLE
Praise!

### ISSUE THREAD

**Issue by olavbm** [wbolster/emacs-python-pytest#66]
I use this all the time every single day of my work.
It is just a piece of software that does one job, and does it well.
Thank you for creating this piece of art.

https://github.com/wbolster/emacs-python-pytest#contributing mentions using the issue tracker for praise.

**Comment by wbolster** [comment]
you're welcome. thanks for taking the time to send this! nice counterbalance to the ‘something does _not_ work’ issues my projects usually receive 😄
