### ISSUE TITLE
Make python-pytest work on Microsoft Windows

### ISSUE THREAD

**Issue by torhtoot** [wbolster/emacs-python-pytest#69]
Currently comint is called with `sh` as the shell command, which is not available on Windows. This could be changed to `cmd` if Windows is detected as the current OS:
```
(let ((shell-command "sh")
     (shell-command-switch "-c"))
  (when (eq system-type 'windows-nt)
    (setq shell-command "cmd")
    (setq shell-command-switch "/c"))
  (make-comint-in-buffer "pytest" buffer shell-command nil shell-command-switch command))
```

**Comment by MagielBruntink** [comment]
It seems https://github.com/wbolster/emacs-python-pytest/commit/7e8acc0232355db35dc66a15bf50c14a80ba3e72 fixed this.
