### ISSUE TITLE
make next-error work

### ISSUE THREAD

**Issue by wbolster** [wbolster/emacs-python-pytest#7]
some `next-error` integration would be nice, since pytest produces file names and line numbers.

**Comment by valignatev** [comment]
I (and many others) would love to see this

**Comment by wbolster** [comment]
@valignatev i just added some code in 09ad688 that makes the basic case work for me.

please give it a try (should appear on melpa soon) and report back!

**Comment by valignatev** [comment]
Thanks! Will definitely try it out

**Comment by valignatev** [comment]
So far it works for me, thanks again!

**Comment by wbolster** [comment]
cool 😎 thanks for letting me know
