### ISSUE TITLE
Use `completing-read-multiple` for multiple files selection

### ISSUE THREAD

**Issue by meliache** [wbolster/emacs-python-pytest#72]
I would prefer if the package used `completing-read-multiple` in `python-pytest--select-test-files` rather than just `completing-read` in a while loop with an extra candidate to finish completion. In `python-pytest--select-test-files`, the final part of the function body could be simplified to `(completing-read-multiple "Choose test files: " candidates)`. The user can then just use normal interactive completion to select a file and if they want to select multiple files, they just enter a comma or whatever their value of `crm-separator` is. The advantage is that it requires less user inputs if the user just wants to select a single file or diretory and you don't need to rely on the user finding the special "finish completion" candidate.

**Comment by wbolster** [comment]
yeah, makes total sense, guess i wasn't aware of that when i built the convoluted logic before. fixed via https://github.com/wbolster/emacs-python-pytest/commit/f945da654dd5dea8ed45b2b5f9ce70def00671d2
